version: '2'
services:

  front-envoy:
    build:
      context: ../
      dockerfile: envoy-front-proxy-random-service/Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
      - ERROR_PERCENTAGE=0
      - TIMEOUT_PERCENTAGE=0
    expose:
      - "80"

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
      - ERROR_PERCENTAGE=15
      - TIMEOUT_PERCENTAGE=5
    expose:
      - "80"

  service3:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service3
    environment:
      - SERVICE_NAME=3
      - ERROR_PERCENTAGE=35
      - TIMEOUT_PERCENTAGE=15
    expose:
      - "80"

  service_slow:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_slow
    environment:
      - SERVICE_NAME=_slow
      - ERROR_PERCENTAGE=0
      - TIMEOUT_PERCENTAGE=50
    expose:
      - "80"

networks:
  envoymesh: {}
